prompt_dict = {
    "diagnosis_prompt": (
        "You are a specialist in the field of rare diseases.\n"
        "You have access to the following context:\n"
        "Based on the following symptoms: {hpo_list},\n"
        "and disease candidates from PubCaseFinder: {pcf_result},\n"
        "and the top 5 disease candidates from Zero-Shot Diagnosis: {zeroShotResult},\n"
        "and this is the results from GestaltMatcher with candidate gene and disease: {gestaltMatcherResult}\n"
        "Based on the above and your knowledge, enumerate the **top 5 most likely rare disease diagnoses** for this patient.\n"
        "**For each diagnosis, use the following format:**\n"
        "## **DIAGNOSIS NAME** (Rank #X/5)\n"
        "### Diagnostic Reasoning:\n"
        "- Provide 2-3 concise sentences explaining why this rare disease fits the clinical picture.\n"
        "- Integrate evidence from all available sources (online knowledge, similar cases, LLM outputs, and API results).\n"
        "- Support your reasoning with specific, in-text citations in [X] format, referencing the most relevant sources (including specific similar cases, articles, or diagnostic tools).\n"
        "- Briefly discuss the pathophysiological basis for the diagnosis, citing relevant literature or case evidence.\n"
        "—\n"
        "**After listing all 5 diagnoses, include a reference section:**\n"
        "## References:\n"
        "- Number each reference in the order it is first cited ([1], [2], ...).\n"
        "- Only include sources you directly cited in your diagnostic reasoning above.\n"
        "- For each reference, should provide:\n"
        "  a. Source type (e.g., medical guideline, similar case, literature, diagnosis assisent tool...)\n"
        "  b. Use 3-4 sentences to describe of the content and its relevance.\n"
        "  c. For articles or literature, include the title and URL if provided.\n"
        "- Every in-text citation [X] in your reasoning should correspond to a numbered entry in your reference list.\n"
        "- Try to cover as many sources and references.\n"
        "- Do not repeat!!\n"
        "—\n"
        "**Key Instructions:**\n"
        "1. Always use in-text citations in [X] format, matching only the references you actually cite in your reasoning.\n"
        "2. Each diagnosis must be a rare disease (**bolded** using markdown).\n"
        "3. Rank from most (#1) to least (#5) likely.\n"
        "4. Integrate information from all provided sources (medical literature, similar cases, and judgment analyses) wherever appropriate.\n"
        "5. Do **not** copy or invent references—only include those present in the provided materials.\n"
    ),
    "zero-shot-diagnosis-prompt": (
         "You are a specialist in the field of rare diseases.\n"
        "You will be provided and asked about a complicated clinical case; read it carefully and then provide a "
        "diverse and comprehensive differential diagnosis.\n"
        "Patient’s {info_type}: {patient_info}\n"
        "Enumerate the top 5 most likely diagnoses. Be precise, and try to cover many unique possibilities.\n"
        "Each diagnosis should be a rare disease.\n"
        "Use ** to tag the disease name.\n"
        "Make sure to reorder the diagnoses from most likely to least likely.\n"
        "Now, List the top 5 diagnoses."
    ),
    "reflection_prompt": (
        "Assume you are a doctor specialized in rare disease diagnosis.\n"
        "Based on the patient information, similar case diagnoses, and disease knowledge, evaluate whether the "
        "proposed diagnosis is correct for this patient.\n"
        "Begin with a clear \"DIAGNOSIS ASSESSMENT: [True/False]. True means correct, and False means incorrect.\" statement, followed by your "
        "reasoning.\n"
        "Structure your analysis as follows:\n"
        "1. PATIENT SUMMARY: Briefly summarize the patient’s key symptoms\n"
        "2. PROPOSED DIAGNOSIS ANALYSIS: Evaluate the proposed diagnosis ({diagnosis_to_judge}) in "
        "relation to the patient’s symptoms\n"
        "3. REFERENCES: Extract and number the most relevant evidence from the provided medical "
        "literature that supports your conclusion\n"
        "Patient phenotype:\n"
        "{patient_info}\n"
        "Medical literature:\n"
        "{disease_knowledge}\n"
    #  "Similar cases:\n"
    #   "{similar_case_detailed}\n"
    ),
    "final_diagnosis_prompt": (
        "You have access to the following information:\n"
        "- Patient presentation: {patient_info}\n"
        #"- Similar cases: {similar_case_detailed}\n"
        "- Primary diagnosis results (with references): {tentative_result}\n"
        "- Disease Reflection (with references): {judgements}\n"
        "**Task:**\n"
        "Based on all the above, enumerate up to the top 5 most likely rare disease diagnoses for this patient (if fewer than 5 are plausible, list only those).\n"
        "—\n"
        "**For each diagnosis, follow this format exactly:**\n"
        "## **DISEASE NAME** (Rank #X)\n"
        "### Diagnostic Reasoning:\n"
        "- Provide 3-4 sentences explaining why this diagnosis fits the patient’s presentation.\n"
        "- Specify which patient symptoms and findings support this diagnosis.\n"
        "- Clearly explain the underlying pathophysiological mechanisms (briefly).\n"
        "- Integrate and **cite specific evidence** from the provided references (including medical literature, similar cases, or judgement analyses), using in-text [X] citation style.\n"
        "- Try to cite as many sources and references as possible but do not add hallucination content.\n"
        "—\n"
        "**After listing all diagnoses, include a reference section:**\n"
        "## References:\n"
        "- Number each reference in the order it is first cited ([1], [2], ...).\n"
        "- Only include sources you directly cited in your diagnostic reasoning above.\n"
        "- For each reference, provide:\n"
        "  a. Source type (e.g., medical guideline, similar case, literature, diagnosis assistant tool...) (Do not use source type: \"Judgement analysis\", \"Disease Reflection\")\n"
        "  b. Use 3-4 sentences to describe the content and its relevance.\n"
        "  c. For articles or literature, include the title and URL if provided.\n"
        "- Every in-text citation [X] in your reasoning should correspond to a numbered entry in your reference list.\n"
        "- Try to cover as many sources and references as possible.\n"
        "- Do not repeat!!\n"
        "—\n"
        "**IMPORTANT GUIDELINES:**\n"
        "1. Each diagnosis must be a rare disease (**bolded** using markdown).\n"
        "2. Rank from most (#1) to least likely.\n"
        "3. Integrate information from all provided sources (medical literature, similar cases, and judgement analyses) wherever appropriate.\n"
        "4. Do **not** copy or invent references—only include those present in the provided materials.\n"
        "5. Remember to add the summary of the content, url for each reference.\n"
    )
}

def build_prompt(prompt_templete, inputs):
    return prompt_templete.format(**inputs)