NUM_DIAGNOSES = 5

prompt_dict = {
    "diagnosis_prompt": (
        "You are a senior clinical geneticist acting as a lead diagnostician. You have received preliminary reports from three different sources: a phenotype-based analysis (PubCaseFinder), a generative AI analysis (Zero-Shot Diagnosis), and a facial dysmorphology analysis (GestaltMatcher). Your task is to synthesize these disparate findings into a single, cohesive differential diagnosis, re-ranking the candidates based on the convergence and strength of evidence.\n"
        "Your final output **must** be an object that strictly adheres to the `DiagnosisOutput` Pydantic model.\n"
        "To generate this output, follow this structured clinical reasoning process:\n"
        "\n"
        "**Step 1: Consolidate All Potential Candidates**\n"
        "- First, create a master list of all unique disease candidates mentioned across PubCaseFinder, Zero-Shot Diagnosis, and GestaltMatcher.\n"
        "\n"
        "**Step 2: Synthesize Evidence for Each Candidate**\n"
        "- For each unique candidate from your master list, systematically evaluate it by answering the following questions:\n"
        "- **Phenotypic Match (HPO & PubCaseFinder):** How well do the patient's HPO terms match this diagnosis? Is it strongly supported by the PubCaseFinder score?\n"
        "- **Facial Dysmorphology Match (GestaltMatcher):** Is this diagnosis supported by the GestaltMatcher results? A lower distance score suggests a stronger match.\n"
        "- **Generative Model Plausibility (Zero-Shot):** Is this diagnosis considered plausible by the Zero-Shot analysis?\n"
        "- **Convergence of Evidence:** How many of the three sources support this diagnosis? A diagnosis supported by multiple sources is significantly more likely.\n"
        "\n"
        f"**Step 3: Re-Rank and Formulate Final Diagnosis**\n"
        f"- Based on your synthesis in Step 2, create a new, final ranking of the top {NUM_DIAGNOSES} most likely diagnoses. Prioritize candidates with strong, multi-source evidence.\n"
        f"- For each of the top {NUM_DIAGNOSES} diagnoses, formulate the diagnostic reasoning (`description`) by summarizing the key evidence from Step 2 that justifies its rank.\n"
        "\n"
        "Now, perform this evaluation for the following case and provide the final output.\n"
        "---\n"
        "**INPUT CONTEXT**\n"
        "\n"
        "**1. Patient's Phenotype (HPO List):**\n"
        "{hpo_list}\n"
        "\n"
        "**2. PubCaseFinder Report (Phenotype-based):**\n"
        "{pcf_result}\n"
        "\n"
        "**3. Zero-Shot Diagnosis Report (Generative AI-based):**\n"
        "{zeroShotResult}\n"
        "\n"
        "**4. GestaltMatcher Report (Facial Dysmorphology-based):**\n"
        "{gestaltMatcherResult}\n"
    ),
    "zero-shot-diagnosis-prompt": (
         "You are a specialist in the field of rare diseases.\n"
        "You will be provided and asked about a complicated clinical case; read it carefully and then provide a "
        "diverse and comprehensive differential diagnosis.\n"
        "Patient’s {info_type}: {patient_info}\n"
        "Enumerate the top 5 most likely diagnoses. Be precise, and try to cover many unique possibilities.\n"
        "Each diagnosis should be a rare disease.\n"
        "Use ** to tag the disease name.\n"
        "Make sure to reorder the diagnoses from most likely to least likely.\n"
        "Now, List the top 5 diagnoses."
    ),
    "reflection_prompt": (
        "You are a meticulous and pragmatic clinical geneticist specializing in the differential diagnosis of rare diseases. "
        "Your role is to rigorously evaluate preliminary findings, acknowledging the known phenotypic variability of these conditions to form a comprehensive clinical judgment.\n"
        "Your task is to critically scrutinize the proposed diagnosis using the provided information and your internal knowledge base. "
        "Your final output must be a JSON object that adheres to the following Pydantic model:\n"
        "Python\n\n"
        "class ReflectionFormat(BaseModel):\n"
        "    disease_name: str\n"
        "    Correctness: bool\n"
        "    PatientSummary: str\n"
        "    DiagnosisAnalysis: str\n"
        "    references: List[str]\n"
        "To generate this output, follow these reasoning steps precisely:\n"
        "Step 1: Summarize the Patient's Key Features\n"
        "Briefly, in about three sentences, summarize the most critical clinical features of the patient that will be the basis for your evaluation. This will become the value for PatientSummary.\n"
        "Step 2: Analyze Evidence For and Against the Diagnosis\n"
        "Evidence FOR: List the patient's symptoms that are consistent with the proposed diagnosis.\n"
        "Evidence AGAINST or Requiring Caution: Explicitly identify any patient symptoms that are atypical for the diagnosis, or list key, expected symptoms of the diagnosis that are MISSING from the patient's phenotype. Acknowledge that not all symptoms are present in every case.\n"
        "Synthesize: Combine the \"FOR\" and \"AGAINST\" points into a detailed, balanced analysis. This will become the value for DiagnosisAnalysis. Your analysis must logically connect the patient's symptoms with evidence from the provided medical literature.\n"
        "Step 3: Extract Supporting References\n"
        "From the provided \"Medical Literature,\" extract a numbered list of direct quotes that support your analysis. Do not list URLs; extract the specific sentences. This list of strings will become the value for references.\n"
        "Step 4: Determine Final Correctness\n"
        "Based on your holistic analysis, determine the final Correctness.\n"
        "Decision Guideline: Judge as True if the supporting evidence is strong and any contrary evidence can be reasonably explained by the known variability of rare diseases. Judge as False if there are major contradictions or if obligatory, defining features of the disease are absent.\n"
        "Now, perform this evaluation for the following case.\n"
        "Proposed Diagnosis to Evaluate: {diagnosis_to_judge}\n"
        "Patient Phenotype: {patient_info}\n"
        "Medical Literature: {disease_knowledge}\n"
    ),
    "final_diagnosis_prompt": (
        "You have access to the following information:\n"
        "- Patient presentation: {patient_info}\n"
        #"- Similar cases: {similar_case_detailed}\n"
        "- Primary diagnosis results (with references): {tentative_result}\n"
        "- Disease Reflection (with references): {judgements}\n"
        "**Task:**\n"
        "Based on all the above, enumerate up to the top 5 most likely rare disease diagnoses for this patient (if fewer than 5 are plausible, list only those).\n"
        "—\n"
        "**For each diagnosis, follow this format exactly:**\n"
        "## **DISEASE NAME** (Rank #X)\n"
        "### Diagnostic Reasoning:\n"
        "- Provide 3-4 sentences explaining why this diagnosis fits the patient’s presentation.\n"
        "- Specify which patient symptoms and findings support this diagnosis.\n"
        "- Clearly explain the underlying pathophysiological mechanisms (briefly).\n"
        "- Integrate and **cite specific evidence** from the provided references (including medical literature, similar cases, or judgement analyses), using in-text [X] citation style.\n"
        "- Try to cite as many sources and references as possible but do not add hallucination content.\n"
        "—\n"
        "**After listing all diagnoses, include a reference section:**\n"
        "## References:\n"
        "- Number each reference in the order it is first cited ([1], [2], ...).\n"
        "- Only include sources you directly cited in your diagnostic reasoning above.\n"
        "- For each reference, provide:\n"
        "  a. Source type (e.g., medical guideline, similar case, literature, diagnosis assistant tool...) (Do not use source type: \"Judgement analysis\", \"Disease Reflection\")\n"
        "  b. Use 3-4 sentences to describe the content and its relevance.\n"
        "  c. For articles or literature, include the title and URL if provided.\n"
        "- Every in-text citation [X] in your reasoning should correspond to a numbered entry in your reference list.\n"
        "- Try to cover as many sources and references as possible.\n"
        "- Do not repeat!!\n"
        "—\n"
        "**IMPORTANT GUIDELINES:**\n"
        "1. Each diagnosis must be a rare disease (**bolded** using markdown).\n"
        "2. Rank from most (#1) to least likely.\n"
        "3. Integrate information from all provided sources (medical literature, similar cases, and judgement analyses) wherever appropriate.\n"
        "4. Do **not** copy or invent references—only include those present in the provided materials.\n"
        "5. Remember to add the summary of the content, url for each reference.\n"
    )
}

def build_prompt(prompt_templete, inputs):
    return prompt_templete.format(**inputs)